import {
    // create naive ui
    create,
    // component
    NConfigProvider,
    NMessageProvider,
    NButton,
    NIcon,
    NCard,
    NForm,
    NFormItem,
    NInput,
    NCheckbox,
    NSpace,
    NTable,
    NModal,
    NTab,
    NTabs,
    NTabPane,
    NSelect,
    NCalendar,
    NCarousel,
    NGradientText,
    NPagination,
    NMenu,
    NPopselect,
    NDivider,
    NH1,
    NResult,
    NUpload,
    NUploadDragger,
    NText,
} from 'naive-ui'

const naive = create({
    components: [
        NConfigProvider,
        NMessageProvider,
        NButton,
        NIcon,
        NCard,
        NForm,
        NFormItem,
        NInput,
        NCheckbox,
        NSpace,
        NTable,
        NModal,
        NTab,
        NTabs,
        NTabPane,
        NSelect,
        NGradientText,
        NPagination,
        NMenu,
        NPopselect,
        NDivider,
        NH1,
        NCalendar,
        NResult,
        NSelect,
        NUpload,
        NUploadDragger,
        NText,
    ],
})

export default naive